### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by kmturley** [schroffl/zig-analyzer-vst#1]
Thanks for the amazing work.

It is common practice to add a LICENSE file to your repo, to make clear you intentions regarding the code.

There is a handy guide here it should take just a couple of minutes to add:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

Thank-you!

**Comment by schroffl** [comment]
Just out of interest: What is your motivation for creating this issue? You don't request a specific license (read: you would like to use some code). You're basically just saying that I should add **any** license. Why?

**Comment by kmturley** [comment]
I'm looking to rebrand your plugin as my own, and make lots of money... just kidding!

Creating a public repo, doesn't not allow others to copy code, you still maintain ownership by default. It's good practice to add a LICENSE. 

I didn't specify a license because it's your choice based on whether you want to allow code reuse, and whether for profit or not. Also because if you have used another third-party's code, you need to respect their licenses too.

I'm working on an open source plugin management system https://github.com/studiorack I'm only adding plugins which have source code in GitHub, along with an open-source LICENSE. My project is intended to support and promote open-source plugins!

**Comment by schroffl** [comment]
Sure man, sounds like an awesome project.

I was just confused, because I've never gotten such a generic request on GitHub :)
